# Generated by Django 2.0 on 2018-04-14 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20180414_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='s_dob',
            field=models.DateTimeField(db_column='S_Dob', null=True),
        ),
    ]
