# Generated by Django 2.0 on 2018-04-14 02:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20180414_0237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='s_dob',
            field=models.DateTimeField(db_column='S_Dob', default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
